# How to deploy:
# gcloud app deploy app.yaml

service: dashboardfrontend
runtime: nodejs18

# Force https and redirect http to https
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

env_variables:
  PROD_DOMAINS: ".whiteribbonalliance.org .freelancedatascientist.net"
  MAIN_SUBDOMAIN: "explore"
  ONLY_PMNCH: False

# Environment variables that need to be exposed to the client (with NEXT_PUBLIC_) should be added at build time
build_env_variables:
  NEXT_PUBLIC_WRA_DASHBOARD_API_URL: "https://api.whiteribbonalliance.org/api/v1"
  NEXT_PUBLIC_GOOGLE_ANALYTICS: "G-PQ6PBP7QDG"
