name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
    
env:
  IMAGE_NAME: dashboardfrontend

jobs:

  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        token: ${{ secrets.PAT_TOKEN }}
        # Setup gcloud CLI
    - id: 'auth'
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
        service_account: 'deft-stratum-290216@appspot.gserviceaccount.com'
        project_id: deft-stratum-290216
        export_default_credentials: true

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
      with:
        version: '>= 363.0.0'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: 'Configure Docker'
      run: 'gcloud auth configure-docker'
      
    - name: character-replacement-test
      run: |
        echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-6)" >> $GITHUB_ENV

    - name: Build & Push
      uses: docker/build-push-action@v2
      with:
          context: .
          push: true
          build-args: |
            version=${{ env.GITHUB_SHA_SHORT }}
          tags: gcr.io/deft-stratum-290216/dashboardfrontend:${{ env.GITHUB_SHA_SHORT }}

    - name: Deploy
      run: gcloud app deploy --image-url=gcr.io/deft-stratum-290216/dashboardfrontend:${{ env.GITHUB_SHA_SHORT }}
