name: "Azure: Build and deploy dashboard (Next.js)"

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: pmnch-front # Set this to your application's name
  NODE_VERSION: '18.x' # Set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Create env file
        run: |
          touch .env.local
          echo "NEXT_PUBLIC_WRA_DASHBOARD_API_URL=https://pmnch-api.azurewebsites.net/api/v1" > .env.local
          echo "NEXT_PUBLIC_GOOGLE_ANALYTICS=G-PQ6PBP7QDG" >> .env.local

      - name: Install & build
        run: |
          mv azure-deployment.next.config.js next.config.js
          npm install
          npm run build
          mv ./.next/static ./.next/standalone/.next
          mv ./public ./.next/standalone

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: './.next/standalone'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '.'
